"""
pandabot_core.identity
~~~~~~~~~~~~~~~~~~~~~~
Bot identity and system prompt assembly.

Core builds the base prompt from env vars and feature flags.
Bots inject their own sections via extra_sections.

Env vars consumed:
    BOT_NAME             default "PandaBot"
    BOT_EMOJI            default ""
    HARDWARE_DESCRIPTION default ""
    TZ_NAME              default "UTC"
    SERVER_DESCRIPTION   free-form override; when set, skips auto-build
    OPERATOR_SSH_CMD     optional SSH command shown to the operator
    TAILSCALE_IP         shown in auto-built services block when set

Feature flags read for auto-build (when SERVER_DESCRIPTION is blank):
    ENABLE_JELLYFIN, ENABLE_JENKINS, ENABLE_RIPPING
    JENKINS_JOBS         comma-separated list of job names
    SYSTEMD_SERVICES     comma-separated list of systemd unit names
"""

from __future__ import annotations

import os
import textwrap

from pandabot_core.config import cfg

__all__ = ["build_system_prompt", "bot_name", "bot_emoji", "startup_message"]


def bot_name() -> str:
    return cfg.str("BOT_NAME", "PandaBot")


def bot_emoji() -> str:
    return cfg.str("BOT_EMOJI", "")


def startup_message(version: int | str = "") -> str:
    """One-liner posted to Discord on bot startup."""
    emoji = bot_emoji()
    name = bot_name()
    ver_str = f" v{version}" if version else ""
    prefix = f"{emoji} " if emoji else ""
    env_tag = " [staging]" if cfg.environment == "staging" else ""
    return f"{prefix}**{name}{ver_str}** online{env_tag}"


def _services_block() -> str:
    """Auto-build services paragraph from feature flags, or return SERVER_DESCRIPTION verbatim."""
    override = cfg.str("SERVER_DESCRIPTION", "")
    if override:
        return override.strip().replace("\\n", "\n")

    enable_jellyfin = cfg.flag("ENABLE_JELLYFIN")
    enable_jenkins = cfg.flag("ENABLE_JENKINS")
    enable_ripping = cfg.flag("ENABLE_RIPPING")
    jenkins_jobs = cfg.csv_list("JENKINS_JOBS", "Login_Test,Process_Movies,Nightly_Convert")
    systemd_services = sorted(cfg.csv_set("SYSTEMD_SERVICES", "sunshine,tailscaled,cockpit,ssh"))
    tailscale_ip = cfg.str("TAILSCALE_IP", "")

    lines = ["The server runs:"]
    if enable_jellyfin:
        lines.append("  - Jellyfin (Docker, port 8096) -- media server")
    if enable_jenkins:
        jobs_fmt = ", ".join(jenkins_jobs)
        lines.append(f"  - Jenkins (Docker, port 8080) -- CI/CD server (jobs: {jobs_fmt})")
    for svc in systemd_services:
        lines.append(f"  - {svc} (systemd)")
    if tailscale_ip:
        lines.append(f"  - Tailscale VPN (IP {tailscale_ip})")
    else:
        lines.append("  - Tailscale VPN")
    if enable_ripping:
        lines.append("  - MakeMKV + abcde for disc ripping (udev auto-rip pipeline)")
    return "\n".join(lines)


def build_system_prompt(
    llm_line: str = "",
    extra_sections: list[str] | None = None,
    jenkins_instructions: str = "",
) -> str:
    """
    Assemble the full system prompt.

    Parameters
    ----------
    llm_line            : e.g. "You are powered by claude-haiku-4-5 (provider: anthropic)."
                          Pass empty string to omit.
    extra_sections      : list of additional paragraphs appended after the core prompt.
                          Each bot injects its own instructions here.
    jenkins_instructions: pre-formatted Jenkins block (generated by the bot if ENABLE_JENKINS).
    """
    name = bot_name()
    hardware = cfg.str("HARDWARE_DESCRIPTION", "")
    tz_name = cfg.str("TZ_NAME", "UTC")
    operator_cmd = cfg.str("OPERATOR_SSH_CMD", "")

    services_block = _services_block()

    if operator_cmd:
        operator_block = textwrap.dedent(f"""
        Operator connection: the person chatting with you connects to this server
        from a Windows machine using WSL. Their SSH command is:
          {operator_cmd}
        When advising on server commands that require a remote shell, present them
        in this form: {operator_cmd} "<command>"
        For multi-line scripts, suggest: {operator_cmd} bash << 'EOF' ... EOF
        """).strip()
    else:
        operator_block = ""

    parts = [
        f"You are {name}, a helpful assistant for a home Ubuntu Server machine.",
    ]
    if cfg.environment == "staging":
        parts.append(
            "ENVIRONMENT: staging — this is a test instance. "
            "Changes tested here have not been promoted to production."
        )
    if llm_line:
        parts.append(llm_line)
    parts += [
        services_block,
        "",
    ]
    if hardware:
        parts.append(f"Hardware: {hardware}.")
    parts += [
        f"Server timezone: {tz_name}.",
        "Timestamps in structured tool responses are already converted to server local time.",
        "App Insights data is returned in UTC -- convert to local time when reporting to the user.",
        "",
        "Always call a tool to answer questions about server state -- never guess "
        "or infer from training knowledge. If a tool returns an error, relay the "
        "exact error text rather than paraphrasing it as a configuration problem.",
        "",
        "When the user asks for something at a future time, on a condition, or on a "
        "recurring schedule, call manage_schedule(action='create') rather than "
        "answering immediately.",
        "",
        "Be concise. When reporting log extracts, summarise rather than quoting "
        "everything unless the user asks for raw output.",
    ]
    if jenkins_instructions:
        parts.append(jenkins_instructions)
    if operator_block:
        parts.append(operator_block)
    for section in (extra_sections or []):
        if section:
            parts.append(section)

    return "\n".join(parts)
